### ISSUE TITLE
Create a landing/home page

### ISSUE THREAD

**Issue by alice-sowerby** [PeoplesMomentum/projects#5] opened 2017-06-28 09:40 UTC
Most of the webpages will be made in ActionKit. The landing page will made separately as it needs more customisation. 

Here is a good example of a first page: https://represent.us/
Here is a good example of a form template page: https://act.represent.us/sign/the-problem/

The first page will be a landing page with a photo that shows a “people powered movement” and a simple form to sign on to our email list. (followed by a prompt for additional info: phone number) When you scroll down, you see the various things Momentum is doing. The first page is one of few pages that requires this much customisation.

**Comment by euyterho** [comment] 2017-07-10 21:26
Duplicate of #15, sorry.

**Closed by euyterho** 2017-07-10 21:26 UTC
